// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovuyuspsxdrxrymvdnzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92dXl1c3BzeGRyeHJ5bXZkbnptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTUxMzcsImV4cCI6MjA2MDY3MTEzN30.iRt_ETxI3-b0YGo6VOdKxQ8yvbjV8qrHSrI8N4UFx0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);